# Generated by Django 3.2.5 on 2021-07-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erAIser', '0007_alter_video_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('imagefile', models.FileField(null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
