# Generated by Django 3.2.5 on 2021-07-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erAIser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
