# Generated by Django 3.2.5 on 2021-07-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erAIser', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
