# Generated by Django 3.2.5 on 2021-07-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erAIser', '0003_rename_name_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='content',
        ),
    ]
