# Generated by Django 3.2.5 on 2021-07-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erAIser', '0005_auto_20210711_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='videofile',
        ),
    ]
